'use strict';

/**
 * Bundled MTG set data: set name (lowercase) → set code (uppercase).
 * Sourced from the Scryfall sets list. Used as a fallback when the
 * Scryfall API is unreachable, and pre-loaded as a base layer when
 * the API is available (the API result takes precedence).
 *
 * @type {Record<string, string>}
 */
const BUNDLED_SETS = {
  // ── Core sets ──────────────────────────────────────────────
  'limited edition alpha':                  'LEA',
  'limited edition beta':                   'LEB',
  'unlimited edition':                      '2ED',
  'revised edition':                        '3ED',
  'fourth edition':                         '4ED',
  'fifth edition':                          '5ED',
  'classic sixth edition':                  '6ED',
  'seventh edition':                        '7ED',
  'eighth edition':                         '8ED',
  'ninth edition':                          '9ED',
  'tenth edition':                          '10E',
  'magic 2010':                             'M10',
  'magic 2011':                             'M11',
  'magic 2012':                             'M12',
  'magic 2013':                             'M13',
  'magic 2014 core set':                    'M14',
  'magic 2015 core set':                    'M15',
  'magic origins':                          'ORI',
  'core set 2019':                          'M19',
  'core set 2020':                          'M20',
  'core set 2021':                          'M21',
  'magic: the gathering foundations':       'FDN',

  // ── Old expansions ─────────────────────────────────────────
  'arabian nights':                         'ARN',
  'antiquities':                            'ATQ',
  'legends':                                'LEG',
  'the dark':                               'DRK',
  'fallen empires':                         'FEM',
  'ice age':                                'ICE',
  'homelands':                              'HML',
  'alliances':                              'ALL',
  'mirage':                                 'MIR',
  'visions':                                'VIS',
  'weatherlight':                           'WTH',
  'tempest':                                'TMP',
  'stronghold':                             'STH',
  'exodus':                                 'EXO',
  "urza's saga":                            'USG',
  "urza's legacy":                          'ULG',
  "urza's destiny":                         'UDS',
  'mercadian masques':                      'MMQ',
  'nemesis':                                'NMS',
  'prophecy':                               'PCY',
  'invasion':                               'INV',
  'planeshift':                             'PLS',
  'apocalypse':                             'APC',
  'odyssey':                                'ODY',
  'torment':                                'TOR',
  'judgment':                               'JUD',
  'onslaught':                              'ONS',
  'legions':                                'LGN',
  'scourge':                                'SCG',
  'mirrodin':                               'MRD',
  'darksteel':                              'DST',
  'fifth dawn':                             '5DN',
  'champions of kamigawa':                  'CHK',
  'betrayers of kamigawa':                  'BOK',
  'saviors of kamigawa':                    'SOK',
  'ravnica: city of guilds':                'RAV',
  'guildpact':                              'GPT',
  'dissension':                             'DIS',
  'coldsnap':                               'CSP',
  'time spiral':                            'TSP',
  'planar chaos':                           'PLC',
  'future sight':                           'FUT',
  'lorwyn':                                 'LRW',
  'morningtide':                            'MOR',
  'shadowmoor':                             'SHM',
  'eventide':                               'EVE',
  'shards of alara':                        'ALA',
  'conflux':                                'CON',
  'alara reborn':                           'ARB',
  'zendikar':                               'ZEN',
  'worldwake':                              'WWK',
  'rise of the eldrazi':                    'ROE',
  'scars of mirrodin':                      'SOM',
  'mirrodin besieged':                      'MBS',
  'new phyrexia':                           'NPH',
  'innistrad':                              'ISD',
  'dark ascension':                         'DKA',
  'avacyn restored':                        'AVR',
  'return to ravnica':                      'RTR',
  'gatecrash':                              'GTC',
  "dragon's maze":                          'DGM',
  'theros':                                 'THS',
  'born of the gods':                       'BNG',
  'journey into nyx':                       'JOU',
  'khans of tarkir':                        'KTK',
  'fate reforged':                          'FRF',
  'dragons of tarkir':                      'DTK',
  'battle for zendikar':                    'BFZ',
  'oath of the gatewatch':                  'OGW',
  'shadows over innistrad':                 'SOI',
  'eldritch moon':                          'EMN',
  'kaladesh':                               'KLD',
  'aether revolt':                          'AER',
  'amonkhet':                               'AKH',
  'hour of devastation':                    'HOU',
  'ixalan':                                 'XLN',
  'rivals of ixalan':                       'RIX',
  'dominaria':                              'DOM',
  'guilds of ravnica':                      'GRN',
  'ravnica allegiance':                     'RNA',
  'war of the spark':                       'WAR',
  'throne of eldraine':                     'ELD',
  'theros beyond death':                    'THB',
  'ikoria: lair of behemoths':              'IKO',
  'zendikar rising':                        'ZNR',
  'kaldheim':                               'KHM',
  'strixhaven: school of mages':            'STX',
  'adventures in the forgotten realms':     'AFR',
  'innistrad: midnight hunt':               'MID',
  'innistrad: crimson vow':                 'VOW',
  'kamigawa: neon dynasty':                 'NEO',
  'streets of new capenna':                 'SNC',
  'dominaria united':                       'DMU',
  "the brothers' war":                      'BRO',
  'phyrexia: all will be one':              'ONE',
  'march of the machine':                   'MOM',
  'march of the machine: the aftermath':    'MAT',
  'wilds of eldraine':                      'WOE',
  'the lost caverns of ixalan':             'LCI',
  'murders at karlov manor':                'MKM',
  'outlaws of thunder junction':            'OTJ',
  'bloomburrow':                            'BLB',
  'duskmourn: house of horror':             'DSK',
  'foundations':                            'FDN',
  'aetherdrift':                            'AEI',
  'tarkir: dragonstorm':                    'TDM',

  // ── Masters / Reprint sets ──────────────────────────────────
  'modern masters':                         'MMA',
  'modern masters 2015 edition':            'MM2',
  'modern masters 2017 edition':            'MM3',
  'iconic masters':                         'IMA',
  'masters 25':                             'A25',
  'ultimate masters':                       'UMA',
  'double masters':                         '2XM',
  'double masters 2022':                    '2X2',
  'eternal masters':                        'EMA',
  'time spiral remastered':                 'TSR',
  'innistrad: double feature':              'DBL',
  'dominaria remastered':                   'DMR',
  'ravnica remastered':                     'RVR',

  // ── Conspiracy ─────────────────────────────────────────────
  'conspiracy':                             'CNS',
  'conspiracy: take the crown':             'CN2',

  // ── Commander ──────────────────────────────────────────────
  'commander 2011':                         'CMD',
  'commander 2013':                         'C13',
  'commander 2014':                         'C14',
  'commander 2015':                         'C15',
  'commander 2016':                         'C16',
  'commander 2017':                         'C17',
  'commander 2018':                         'C18',
  'commander 2019':                         'C19',
  'commander 2020':                         'C20',
  'commander 2021':                         'C21',
  'commander anthology':                    'CMA',
  'commander anthology volume ii':          'CM2',
  'commander legends':                      'CMR',
  'commander legends: battle for baldur\'s gate': 'CLB',
  'the lord of the rings: tales of middle-earth commander': 'LTC',
  'commander masters':                      'CMM',
  "doctor who":                             'WHO',
  'murders at karlov manor commander':      'MKC',
  'outlaws of thunder junction commander':  'OTC',
  'bloomburrow commander':                  'BLC',
  'duskmourn: house of horror commander':   'DSC',
  'foundations commander':                  'FDC',

  // ── Special / Supplemental ─────────────────────────────────
  'the lord of the rings: tales of middle-earth': 'LTR',
  'the list':                               'LIST',
  'mystery booster':                        'MB1',
  'mystery booster 2':                      'MB2',
  'jumpstart':                              'JMP',
  'jumpstart 2022':                         'J22',
  'foundations jumpstart':                  'FJB',
  'historic anthology 1':                   'HA1',
  'historic anthology 2':                   'HA2',
  'historic anthology 3':                   'HA3',
  'historic anthology 4':                   'HA4',
  'historic anthology 5':                   'HA5',
  'pioneer masters':                        'PIO',
  'starter commander decks':                'SCD',
  'special guests':                         'SPG',
  'breaking news':                          'OTP',
  'the big score':                          'BIG',

  // ── Promo / Misc ───────────────────────────────────────────
  'prerelease cards':                       'PTC',
  'judge gift cards':                       'JGP',
  'world championship decks':               'WC',
  'anthologies':                            'ATH',
  'battle royale box set':                  'BRB',
  'beatdown box set':                       'BTD',
  'deckmasters':                            'DKM',
  'portal':                                 'POR',
  'portal second age':                      'P02',
  'portal three kingdoms':                  'PTK',
  'starter 1999':                           'S99',
  'starter 2000':                           'S00',
  'unglued':                                'UGL',
  'unhinged':                               'UNH',
  'unstable':                               'UST',
  'unsanctioned':                           'UND',
  'unfinity':                               'UNF',
};

module.exports = BUNDLED_SETS;
